spring:
  application:
    name: auth
  redis:
    host: 47.111.73.225
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 5
        max-wait: 5000
        min-idle: 5
server:
  port: 7071
  servlet:
    context-path: /auth-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    prefer-ip-address: true

